name: OCaml CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ocaml-ci .

      - name: Run dune build
        run: docker run --rm ocaml-ci opam exec -- dune build

      - name: Run tests
        run: docker run --rm ocaml-ci opam exec -- dune runtest